services:
  db:
    image: mysql:8.0
    container_name: two_tier_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: myappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - two-tier-net

  backend:
    build:
      context: ./backend
    container_name: two_tier_backend
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: myappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - two-tier-net

  frontend:
    build:
      context: ./frontend
    container_name: two_tier_frontend
    restart: unless-stopped
    ports:
      - "5001:5000"
    depends_on:
      - backend
    networks:
      - two-tier-net

volumes:
  db_data:

networks:
  two-tier-net:
    driver: bridge
